version: "2"

services:

  samba:
    image: dperson/samba:rpi
    restart: always
    command: '-u "pi;password" -s "media;/media;yes;no"'
    stdin_open: true
    tty: true
    ports:
      - 139:130
      - 445:445
    read_only: false  
    volumes:
      - /usr/share/zoneinfo/America/Bogota:/etc/localtime
      - /home/pi/media:/media